# Generated by Django 3.1.7 on 2021-04-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'airline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'airport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('building_num', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=30)),
                ('passport_num', models.CharField(max_length=20)),
                ('passport_country', models.CharField(max_length=30)),
                ('passport_expire', models.DateField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('airline_name', models.OneToOneField(db_column='airline_name', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.airline')),
                ('flight_num', models.CharField(max_length=30, unique=True)),
                ('depart_date', models.DateField(unique=True)),
                ('depart_time', models.TimeField(unique=True)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('base_price', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'flight',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('airline_name', models.ForeignKey(db_column='airline_name', on_delete=django.db.models.deletion.CASCADE, to='App.airline')),
            ],
            options={
                'db_table': 'staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookingAgent',
            fields=[
                ('agent_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=30, unique=True)),
                ('agent_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'booking_agent',
                'managed': True,
                'unique_together': {('agent_email', 'agent_id')},
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=30, primary_key=True, serialize=False)),
                ('seats', models.IntegerField()),
                ('airline_name', models.ForeignKey(db_column='airline_name', on_delete=django.db.models.deletion.CASCADE, to='App.airline')),
            ],
            options={
                'db_table': 'airplane',
                'managed': True,
                'unique_together': {('id', 'airline_name')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('sold_price', models.CharField(max_length=11)),
                ('airline_name', models.ForeignKey(db_column='airline_name', on_delete=django.db.models.deletion.CASCADE, related_name='Ticket+', to='App.flight')),
                ('depart_date', models.ForeignKey(db_column='depart_date', on_delete=django.db.models.deletion.CASCADE, related_name='Ticket+', to='App.flight', to_field='depart_date')),
                ('depart_time', models.ForeignKey(db_column='depart_time', on_delete=django.db.models.deletion.CASCADE, related_name='Ticket+', to='App.flight', to_field='depart_time')),
                ('flight_num', models.ForeignKey(db_column='flight_num', on_delete=django.db.models.deletion.CASCADE, related_name='Ticket+', to='App.flight', to_field='flight_num')),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhoneNum',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.staff')),
                ('number', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'phone_num',
                'managed': True,
                'unique_together': {('username', 'number')},
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='airplane_id',
            field=models.ForeignKey(db_column='airplane_id', on_delete=django.db.models.deletion.CASCADE, to='App.airplane'),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrive_airport_name',
            field=models.ForeignKey(db_column='arrive_airport_name', on_delete=django.db.models.deletion.CASCADE, related_name='flight+', to='App.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='depart_airport_name',
            field=models.ForeignKey(db_column='depart_airport_name', on_delete=django.db.models.deletion.CASCADE, related_name='flight+', to='App.airport'),
        ),
        migrations.CreateModel(
            name='CustomerPurchase',
            fields=[
                ('ticket_id', models.OneToOneField(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.ticket')),
                ('card_type', models.CharField(max_length=30)),
                ('card_num', models.CharField(max_length=30)),
                ('name_on_card', models.CharField(max_length=30)),
                ('expire_at', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('customer_email', models.ForeignKey(db_column='customer_email', on_delete=django.db.models.deletion.CASCADE, to='App.customer')),
            ],
            options={
                'db_table': 'customer_purchase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AgentPurchase',
            fields=[
                ('ticket_id', models.OneToOneField(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.ticket')),
                ('card_type', models.CharField(max_length=30)),
                ('card_num', models.CharField(max_length=30)),
                ('name_on_card', models.CharField(max_length=30)),
                ('expire_at', models.DateField()),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('agent_email', models.ForeignKey(db_column='agent_email', on_delete=django.db.models.deletion.CASCADE, related_name='agent-purchase+', to='App.bookingagent')),
                ('agent_id', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent-purchase+', to='App.bookingagent', to_field='agent_id')),
                ('customer_email', models.ForeignKey(db_column='customer_email', on_delete=django.db.models.deletion.CASCADE, to='App.customer')),
            ],
            options={
                'db_table': 'agent_purchase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('customer_email', models.OneToOneField(db_column='customer_email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.customer')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('airline_name', models.ForeignKey(db_column='airline_name', on_delete=django.db.models.deletion.CASCADE, related_name='rate+', to='App.flight')),
                ('depart_date', models.ForeignKey(db_column='depart_date', on_delete=django.db.models.deletion.CASCADE, related_name='rate+', to='App.flight', to_field='depart_date')),
                ('depart_time', models.ForeignKey(db_column='depart_time', on_delete=django.db.models.deletion.CASCADE, related_name='rate+', to='App.flight', to_field='depart_time')),
                ('flight_num', models.ForeignKey(db_column='flight_num', on_delete=django.db.models.deletion.CASCADE, related_name='rate+', to='App.flight', to_field='flight_num')),
            ],
            options={
                'db_table': 'rate',
                'managed': True,
                'unique_together': {('customer_email', 'airline_name', 'flight_num', 'depart_time', 'depart_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('airline_name', 'flight_num', 'depart_date', 'depart_time')},
        ),
    ]
